### PR TITLE
prototype gcc build

### PR DESCRIPTION
**Pull request by balcy**

### CODE REVIEW

**Comment by balcy** [comment]
@fredldotme is it possible to get a prototype branch here with write access to try a Jenkins build ?

**Comment by fredldotme** [comment]
@balcy Just pushing/merging to this branch should do it.

**Comment by balcy** [comment]
ah ok I was used to seeing the Jenkins build message in github, now I've found the build, thanks.

**Comment by balcy** [comment]
ok the first step I wanted to try is building https://packages.ubuntu.com/xenial/gcc-5 without additional patches (just as is) with Jenkins.
therefore I ran `dpkg-source -x gcc-5_5.4.0-6ubuntu1~16.04.12.dsc` and started with that debian folder from scratch. (I've created an ubports.source_location file with the archive, too)

In the Jenkins output I get (for amd64 / arm64 / armhf) :
https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fgcc-5/detail/PR-1/11/pipeline
```
-----------------------------------------------------------------------------
The system has no more ptys.  Ask your system administrator to create more.
    while executing
"spawn true"
expect is failing on your system with the above error, which means the GCC
testsuite will fail.  Please resolve the above issues and retry the build.
-----------------------------------------------------------------------------
```
@UniversalSuperBox  @fredldotme  is it possible to create more ptys, or should we try deactivating the tests instead ?
http://www.linuxfromscratch.org/lfs/view/6.3/chapter05/gcc-pass2.html

**Pull request closed without merging**
